var monthText = document.getElementById("monthText");
var titleText1 = document.getElementById("titleText1");
var titleText2 = document.getElementById("titleText2");

var vehiclesTitle = document.getElementById("vehiclesTitle");
var rtext1 = document.getElementById("rtext1");
var rtext2 = document.getElementById("rtext2");
var rtext3 = document.getElementById("rtext3");
var rtext4 = document.getElementById("rtext4");
var rtext5 = document.getElementById("rtext5");
var rtext6 = document.getElementById("rtext6");
var rtext7 = document.getElementById("rtext7");
var rtext8 = document.getElementById("rtext8");
var rtext9 = document.getElementById("rtext9");
var rtext10 = document.getElementById("rtext10");
var rtext11 = document.getElementById("rtext11");
var rtext12 = document.getElementById("rtext12");
var rtext13 = document.getElementById("rtext13");
var rtext14 = document.getElementById("rtext14");
var rtext15 = document.getElementById("rtext15");
var rtext16 = document.getElementById("rtext16");
var rtext17 = document.getElementById("rtext17");
var rtext18 = document.getElementById("rtext18");
var rtext19 = document.getElementById("rtext19");
var rtext20 = document.getElementById("rtext20");
var rtext21 = document.getElementById("rtext21");
var rtext22 = document.getElementById("rtext22");
var rtext23 = document.getElementById("rtext23");
var rtext24 = document.getElementById("rtext24");
var rtext25 = document.getElementById("rtext25");
var ticktext1 = document.getElementById("ticktext1");
var ticktext2 = document.getElementById("ticktext2");
var ticktext3 = document.getElementById("ticktext3");
var ticktext4 = document.getElementById("ticktext4");
var ticktext5 = document.getElementById("ticktext5");
var ticktext6 = document.getElementById("ticktext6");
var ticktext7 = document.getElementById("ticktext7");
var ticktext8 = document.getElementById("ticktext8");
var ticktext9 = document.getElementById("ticktext9");
var ticktext10 = document.getElementById("ticktext10");

var fwres1 = document.getElementById("fwres1");
var fwres2 = document.getElementById("fwres2");
var fwres3 = document.getElementById("fwres3");
var fwres4 = document.getElementById("fwres4");
var fwres5 = document.getElementById("fwres5");
var fwres6 = document.getElementById("fwres6");
var fwres7 = document.getElementById("fwres7");
var fwres8 = document.getElementById("fwres8");
var fwres9 = document.getElementById("fwres9");
var fwres10 = document.getElementById("fwres10");
var fwres11 = document.getElementById("fwres11");
var fwres12 = document.getElementById("fwres12");
var fwres13 = document.getElementById("fwres13");
var fwres14 = document.getElementById("fwres14");
var fwres15 = document.getElementById("fwres15");
var fwres16 = document.getElementById("fwres16");
var fwres17 = document.getElementById("fwres17");
var fwres18 = document.getElementById("fwres18");
var fwres19 = document.getElementById("fwres19");
var fwres20 = document.getElementById("fwres20");
var fwres21 = document.getElementById("fwres21");
var fwres22 = document.getElementById("fwres22");
var fwres23 = document.getElementById("fwres23");
var fwres24 = document.getElementById("fwres24");
var fwres25 = document.getElementById("fwres25");

var swres1 = document.getElementById("swres1");
var swres2 = document.getElementById("swres2");
var swres3 = document.getElementById("swres3");
var swres4 = document.getElementById("swres4");
var swres5 = document.getElementById("swres5");
var swres6 = document.getElementById("swres6");
var swres7 = document.getElementById("swres7");
var swres8 = document.getElementById("swres8");
var swres9 = document.getElementById("swres9");
var swres10 = document.getElementById("swres10");
var swres11 = document.getElementById("swres11");
var swres12 = document.getElementById("swres12");
var swres13 = document.getElementById("swres13");
var swres14 = document.getElementById("swres14");
var swres15 = document.getElementById("swres15");
var swres16 = document.getElementById("swres16");
var swres17 = document.getElementById("swres17");
var swres18 = document.getElementById("swres18");
var swres19 = document.getElementById("swres19");
var swres20 = document.getElementById("swres20");
var swres21 = document.getElementById("swres21");
var swres22 = document.getElementById("swres22");
var swres23 = document.getElementById("swres23");
var swres24 = document.getElementById("swres24");


var fwrestext1 = document.getElementById("fwrestext1");
var fwrestext2 = document.getElementById("fwrestext2");
var fwrestext3 = document.getElementById("fwrestext3");
var fwrestext4 = document.getElementById("fwrestext4");
var fwrestext5 = document.getElementById("fwrestext5");
var fwrestext6 = document.getElementById("fwrestext6");
var fwrestext7 = document.getElementById("fwrestext7");
var fwrestext8 = document.getElementById("fwrestext8");
var fwrestext9 = document.getElementById("fwrestext9");
var fwrestext10 = document.getElementById("fwrestext10");
var fwrestext11 = document.getElementById("fwrestext11");
var fwrestext12 = document.getElementById("fwrestext12");
var fwrestext13 = document.getElementById("fwrestext13");
var fwrestext14 = document.getElementById("fwrestext14");
var fwrestext15 = document.getElementById("fwrestext15");
var fwrestext16 = document.getElementById("fwrestext16");
var fwrestext17 = document.getElementById("fwrestext17");
var fwrestext18 = document.getElementById("fwrestext18");
var fwrestext19 = document.getElementById("fwrestext19");
var fwrestext20 = document.getElementById("fwrestext20");
var fwrestext21 = document.getElementById("fwrestext21");
var fwrestext22 = document.getElementById("fwrestext22");
var fwrestext23 = document.getElementById("fwrestext23");
var fwrestext24 = document.getElementById("fwrestext24");
var fwrestext25 = document.getElementById("fwrestext25");

var swrestext1 = document.getElementById("swrestext1");
var swrestext2 = document.getElementById("swrestext2");
var swrestext3 = document.getElementById("swrestext3");
var swrestext4 = document.getElementById("swrestext4");
var swrestext5 = document.getElementById("swrestext5");
var swrestext6 = document.getElementById("swrestext6");
var swrestext7 = document.getElementById("swrestext7");
var swrestext8 = document.getElementById("swrestext8");
var swrestext9 = document.getElementById("swrestext9");
var swrestext10 = document.getElementById("swrestext10");
var swrestext11 = document.getElementById("swrestext11");
var swrestext12 = document.getElementById("swrestext12");
var swrestext13 = document.getElementById("swrestext13");
var swrestext14 = document.getElementById("swrestext14");
var swrestext15 = document.getElementById("swrestext15");
var swrestext16 = document.getElementById("swrestext16");
var swrestext17 = document.getElementById("swrestext17");
var swrestext18 = document.getElementById("swrestext18");
var swrestext19 = document.getElementById("swrestext19");
var swrestext20 = document.getElementById("swrestext20");
var swrestext21 = document.getElementById("swrestext21");
var swrestext22 = document.getElementById("swrestext22");
var swrestext23 = document.getElementById("swrestext23");
var swrestext24 = document.getElementById("swrestext24");
var swrestext25 = document.getElementById("swrestext25");






malibuReservations(fwres1, swres1);
transitReservations(fwres2, swres2);
tahoeReservations(fwres3, swres3);
silveradoReservations(fwres4, swres4);
expeditionReservations(fwres5, swres5);
expressReservations(fwres6, swres6);
i622013Reservations(fwres7, swres7);
i622014Reservations(fwres8, swres8);
i622015Reservations(fwres9, swres9);
i622016Reservations(fwres10, swres10);
suburbanReservations(fwres11, swres11);
californiaReservations(fwres13, swres13);
idahoReservations(fwres14, swres14);
montanaReservations(fwres15, swres15);
nevadaReservations(fwres16, swres16);
newmexicoReservations(fwres17, swres17);
oregonReservations(fwres18, swres18);
utahReservations(fwres19, swres19);
washingtonReservations(fwres20, swres20);
wyomingReservations(fwres21, swres21);
b203Reservations(fwres22, swres22);
b204Reservations(fwres23, swres23);
b205Reservations(fwres24, swres24);
b207Reservations(fwres25, swres25);

titleText1.innerHTML = "";
titleText2.innerHTML = "Resource Reservations";
monthText.innerHTML = currmonth();
vehiclesTitle.innerHTML = "Vehicles";
rtext1.innerHTML = "Chevy Malibu";
rtext2.innerHTML = "Ford Transit";
rtext3.innerHTML = "Chevy Tahoe";
rtext4.innerHTML = "Chevy Silverado";
rtext5.innerHTML = "Ford Expedition";
rtext6.innerHTML = "Chevy Express";
rtext7.innerHTML = "Ford Van";
rtext8.innerHTML = "Ford Van";
rtext9.innerHTML = "Ford Van";
rtext10.innerHTML = "Ford Van";
rtext11.innerHTML = "Chevy Suburban";
rtext12.innerHTML = "Rooms";
rtext13.innerHTML = "California";
rtext14.innerHTML = "Idaho";
rtext15.innerHTML = "Montana";
rtext16.innerHTML = "Nevada";
rtext17.innerHTML = "New Mexico";
rtext18.innerHTML = "Oregon";
rtext19.innerHTML = "Utah";
rtext20.innerHTML = "Washington ABC";
rtext21.innerHTML = "Wyoming";
rtext22.innerHTML = "Conference";
rtext23.innerHTML = "Conference";
rtext24.innerHTML = "Conference";
rtext25.innerHTML = "Conference";

ticktext1.innerHTML = firstMon(today);
ticktext2.innerHTML = firstTue(today);
ticktext3.innerHTML = firstWed(today);
ticktext4.innerHTML = firstThu(today);
ticktext5.innerHTML = firstFri(today);
ticktext6.innerHTML = secondMon(today);
ticktext7.innerHTML = secondTue(today);
ticktext8.innerHTML = secondWed(today);
ticktext9.innerHTML = secondThu(today);
ticktext10.innerHTML = secondFri(today);
